# Generated by Django 5.1.4 on 2024-12-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_party_candidate_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='party',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
